teams:
  - name: bots
    maintainers:
      - lfdt-bot
    members:
      - thelinuxfoundation
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - thelinuxfoundation
  - name: verii-maintainers
    maintainers:
      - sloops77
    members:

repositories:
  - name: .github
    teams:
      bots: maintain
      lf-staff: maintain
      verii-maintainers: admin
    visibility: public
  - name: core
    teams:
      bots: maintain
      verii-maintainers: admin
    visibility: public
  - name: governance
    teams:
      bots: maintain
      lf-staff: maintain
      verii-maintainers: maintain
    visibility: public
